
 //export const images = import.meta.glob('/src/assets/images/**/*.(jpg|jpeg|png)');
  
 //Imagenes para importar:
 export const images = {
  '00032405023bolsas-polietileno.jpg': '/src/assets/images/00032405023bolsas-polietileno.jpg',
  'bolsa-de-plastico-polietileno-en-rollo-1.jpg': '/src/assets/images/bolsa-de-plastico-polietileno-en-rollo-1.jpg',
  'bolsas-de-polietileno-natural.jpg': '/src/assets/images/bolsas-de-polietileno-natural.jpg',
  'bolsa-de-plastico-polietileno-alta-densidad.jpg': '/src/assets/images/bolsa-de-plastico-polietileno-alta-densidad.jpg',
  'bolsa-de-plastico-tipo-camiseta-1.jpg': '/src/assets/images/bolsa-de-plastico-tipo-camiseta-1.jpg',
  'Bolsas-camisetas.jpg': '/src/assets/images/Bolsas-camisetas.jpg',
  'camisetas.jpg': '/src/assets/images/camisetas.jpg',
  'lamina-folex.png': '/src/assets/images/lamina-folex.png',
  'folex son buenas.jpg': '/src/assets/images/folex son buenas.jpg',
  'bolsa-negra-01.jpg': '/src/assets/images/bolsa-negra-01.jpg',
  'leña.jpg': '/src/assets/images/leña.jpg',
  'bolsas para horno.jpg': '/src/assets/images/bolsas para horno.jpg',
  'Emblocadas.jpg': '/src/assets/images/Emblocadas.jpg',
  'rollos rendidor.jpg': '/src/assets/images/rollos rendidor.jpg',
  'polipropileno.jpg': '/src/assets/images/polipropileno.jpg',
  'rinon.jpg': '/src/assets/images/rinon.jpg',
  'bolsaspapel.jpg': '/src/assets/images/bolsaspapel.jpg',
  'caja masas.jpg': '/src/assets/images/caja masas.jpg',
  'cajas tortas cartulina.jpg': '/src/assets/images/cajas tortas cartulina.jpg',
  'caja-pizza.png': '/src/assets/images/caja-pizza.png',
  'caja-pizza-oct.jpg': '/src/assets/images/caja-pizza-oct.jpg',
  'caja-pizza-micro.jpg': '/src/assets/images/caja-pizza-micro.jpg',
  'caja-lomo.jpg': '/src/assets/images/caja-lomo.jpg',
  'caja-empanadas.jpeg': '/src/assets/images/caja-empanadas.jpeg',
  'caja-media.jpg': '/src/assets/images/caja-media.jpg',
  'cono-papas.jpeg': '/src/assets/images/cono-papas.jpeg',
  'bandeja-de-carton.jpg': '/src/assets/images/bandeja-de-carton.jpg',
  'bandeja-carton1.jpg': '/src/assets/images/bandeja-carton1.jpg',
  'redondas-doradas.jpg': '/src/assets/images/redondas-doradas.jpg',
  'papel-resma.jpg': '/src/assets/images/papel-resma.jpg',
  'bobina papel.jpg': '/src/assets/images/bobina papel.jpg',
  'obleas 618.png': '/src/assets/images/obleas 618.png',
  'expandido 617.jpg': '/src/assets/images/expandido 617.jpg',
  'expandido 618.jpg': '/src/assets/images/expandido 618.jpg',
  'expandido-625.jpg': '/src/assets/images/expandido-625.jpg',
  'expandido 628.jpg': '/src/assets/images/expandido 628.jpg',
  'Bandejas-Plasticas.jpg': '/src/assets/images/Bandejas-Plasticas.jpg',
  'ensaladera.jpg': '/src/assets/images/ensaladera.jpg',
  'cinta-adhesiva.png': '/src/assets/images/cinta-adhesiva.png',
  'cinta-48.jpg': '/src/assets/images/cinta-48.jpg',
  'Cubiertos.jpg': '/src/assets/images/Cubiertos.jpg',
  'cuchara.jpg': '/src/assets/images/cuchara.jpg',
  'cucharas-sundae.jpg': '/src/assets/images/cucharas-sundae.jpg',
  'agitadores.jpg': '/src/assets/images/agitadores.jpg',
};
